package br.com.model;

// Generated 08/03/2012 15:36:20 by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * Compraitem generated by hbm2java
 */
@Entity
@Table(name = "compraitem", catalog = "qualisono")
public class CompraItem implements java.io.Serializable {

	private Integer codigo;
	private Produto produto;
	private Compra compra;
	private Unidade unidade;
	private Integer quantidade;
	private double vtotal;
	private double bcicms;
	private double vicms;
	private double vipi;
	private double aicms;
	private double aipi;

	public CompraItem() {
	}

	public CompraItem(Produto produto, Compra compra, Unidade unidade,
			Integer quantidade, double vtotal, double bcicms, double vicms,
			double vipi, double aicms, double aipi) {
		this.produto = produto;
		this.compra = compra;
		this.unidade = unidade;
		this.quantidade = quantidade;
		this.vtotal = vtotal;
		this.bcicms = bcicms;
		this.vicms = vicms;
		this.vipi = vipi;
		this.aicms = aicms;
		this.aipi = aipi;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false)
	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cProd", nullable = false)
	public Produto getProduto() {
		return this.produto;
	}

	public void setProduto(Produto produto) {
		this.produto = produto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "compra", nullable = false)
	public Compra getCompra() {
		return this.compra;
	}

	public void setCompra(Compra compra) {
		this.compra = compra;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unidade", nullable = false)
	public Unidade getUnidade() {
		return this.unidade;
	}

	public void setUnidade(Unidade unidade) {
		this.unidade = unidade;
	}

	@NotNull(message="Campo Quantidade: Obrigatório")
	@Column(name = "quantidade", nullable = false)
	public Integer getQuantidade() {
		return this.quantidade;
	}

	public void setQuantidade(Integer quantidade) {
		this.quantidade = quantidade;
	}

	@Column(name = "vtotal", nullable = false, precision = 15)
	public double getVtotal() {
		return this.vtotal;
	}

	public void setVtotal(double vtotal) {
		this.vtotal = vtotal;
	}

	@Column(name = "bcicms", nullable = false, precision = 15)
	public double getBcicms() {
		return this.bcicms;
	}

	public void setBcicms(double bcicms) {
		this.bcicms = bcicms;
	}

	@Column(name = "vicms", nullable = false, precision = 15)
	public double getVicms() {
		return this.vicms;
	}

	public void setVicms(double vicms) {
		this.vicms = vicms;
	}

	@Column(name = "vipi", nullable = false, precision = 15)
	public double getVipi() {
		return this.vipi;
	}

	public void setVipi(double vipi) {
		this.vipi = vipi;
	}

	@Column(name = "aicms", nullable = false, precision = 15)
	public double getAicms() {
		return this.aicms;
	}

	public void setAicms(double aicms) {
		this.aicms = aicms;
	}

	@Column(name = "aipi", nullable = false, precision = 15)
	public double getAipi() {
		return this.aipi;
	}

	public void setAipi(double aipi) {
		this.aipi = aipi;
	}

}
