package br.com.model;

// Generated 08/03/2012 15:36:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.LazyToOne;
import org.hibernate.annotations.LazyToOneOption;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * Contasapagar generated by hbm2java
 */
@Entity
@Table(name = "contasapagar", catalog = "qualisono")
public class Contasapagar implements java.io.Serializable {

	private Integer codigo;
//	private Fornecedor fornecedor;
	private Unidade unidade;
	private String categoria;
	private Integer opcaocategoria;
	private Date mesreferencia;
	private String tipodoc;
	private Compra compra;
	private Double valor;
	private Date datavencimento;
	private Integer parcela;
	private Integer dia;
	private Set<Parcelasapagar> parcelasapagars = new HashSet<Parcelasapagar>(0);

	public Contasapagar() {
	}

	public Contasapagar(Unidade unidade, String categoria, Date datavencimento,
			Integer parcela, Integer dia, Integer opcaocategoria) {
		this.unidade = unidade;
		this.categoria = categoria;
		this.opcaocategoria = opcaocategoria;
		this.datavencimento = datavencimento;
		this.parcela = parcela;
		this.dia = dia;
	}

	public Contasapagar(Unidade unidade, Integer opcaocategoria,
			String categoria, Date mesreferencia, String tipodoc,
			Compra compra, Double valor, Date datavencimento, Integer parcela,
			Integer dia, Set<Parcelasapagar> parcelasapagars) {
//		this.fornecedor = fornecedor;
		this.unidade = unidade;
		this.categoria = categoria;
		this.mesreferencia = mesreferencia;
		this.tipodoc = tipodoc;
		this.compra = compra;
		this.valor = valor;
		this.datavencimento = datavencimento;
		this.parcela = parcela;
		this.dia = dia;
		this.parcelasapagars = parcelasapagars;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false)
	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

//	@LazyToOne(LazyToOneOption.FALSE)
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "fornecedor")
//	public Fornecedor getFornecedor() {
//		return this.fornecedor;
//	}
//
//	public void setFornecedor(Fornecedor fornecedor) {
//		this.fornecedor = fornecedor;
//	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unidade", nullable = false)
	public Unidade getUnidade() {
		return this.unidade;
	}

	public void setUnidade(Unidade unidade) {
		this.unidade = unidade;
	}

	@NotEmpty(message="Campo Categoria: Obrigatório")
	@Length(min=1, max=20, message="Campo Usuário: Tamanho mínimo de 1 caracteres")
	@Column(name = "categoria", nullable = false, length = 20)
	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}
	
	@NotNull(message="Campo Opção Categoria: Obrigatório")
	@Column(name = "opcaocategoria", nullable = false)
	public Integer getOpcaocategoria() {
		return this.opcaocategoria;
	}

	public void setOpcaocategoria(Integer opcaocategoria) {
		this.opcaocategoria = opcaocategoria;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "mesreferencia", length = 10)
	public Date getMesreferencia() {
		return this.mesreferencia;
	}

	public void setMesreferencia(Date mesreferencia) {
		this.mesreferencia = mesreferencia;
	}

	@NotEmpty(message="Campo Tipo Documento: Obrigatório")
	@Length(min=1, max=20, message="Campo Tipo Documento: Tamanho mínimo de 1 caracteres")
	@Column(name = "tipodoc", length = 20)
	public String getTipodoc() {
		return this.tipodoc;
	}

	public void setTipodoc(String tipodoc) {
		this.tipodoc = tipodoc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "compra")
	public Compra getCompra() {
		return this.compra;
	}

	public void setCompra(Compra compra) {
		this.compra = compra;
	}

	@NotNull(message="Campo Valor: Obrigatório")
	@Column(name = "valor", precision = 13)
	public Double getValor() {
		return this.valor;
	}

	public void setValor(Double valor) {
		this.valor = valor;
	}

	@NotNull(message="Campo Data Vencimento: Obrigatório")
	@Temporal(TemporalType.DATE)
	@Column(name = "datavencimento", nullable = false, length = 10)
	public Date getDatavencimento() {
		return this.datavencimento;
	}

	public void setDatavencimento(Date datavencimento) {
		this.datavencimento = datavencimento;
	}

	@NotNull(message="Campo Parcela: Obrigatório")
	@Column(name = "parcela", nullable = false)
	public Integer getParcela() {
		return this.parcela;
	}

	public void setParcela(Integer parcela) {
		this.parcela = parcela;
	}

	@NotNull(message="Campo Dia: Obrigatório")
	@Column(name = "dia", nullable = false)
	public Integer getDia() {
		return this.dia;
	}

	public void setDia(Integer dia) {
		this.dia = dia;
	}

	@LazyToOne(LazyToOneOption.FALSE)
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contasapagar", cascade = CascadeType.ALL)
	public Set<Parcelasapagar> getParcelasapagars() {
		return this.parcelasapagars;
	}

	public void setParcelasapagars(Set<Parcelasapagar> parcelasapagars) {
		this.parcelasapagars = parcelasapagars;
	}

}
