package br.com.model;

// Generated 08/03/2012 15:36:20 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Geral generated by hbm2java
 */
@Entity
@Table(name = "geral", catalog = "qualisono", uniqueConstraints = @UniqueConstraint(columnNames = {
		"unidade", "grupo", "chave" }))
public class Geral implements java.io.Serializable {

	private Integer codigo;
	private Unidade unidade;
	private String grupo;
	private String chave;
	private String descricao;
	private String valor;

	public Geral() {
	}

	public Geral(Unidade unidade, String grupo, String chave, String valor) {
		this.unidade = unidade;
		this.grupo = grupo;
		this.chave = chave;
		this.valor = valor;
	}

	public Geral(Unidade unidade, String grupo, String chave, String descricao,
			String valor) {
		this.unidade = unidade;
		this.grupo = grupo;
		this.chave = chave;
		this.descricao = descricao;
		this.valor = valor;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false)
	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unidade", nullable = false)
	public Unidade getUnidade() {
		return this.unidade;
	}

	public void setUnidade(Unidade unidade) {
		this.unidade = unidade;
	}

	@Column(name = "grupo", nullable = false, length = 20)
	public String getGrupo() {
		return this.grupo;
	}

	public void setGrupo(String grupo) {
		this.grupo = grupo;
	}

	@Column(name = "chave", nullable = false, length = 20)
	public String getChave() {
		return this.chave;
	}

	public void setChave(String chave) {
		this.chave = chave;
	}

	@Column(name = "descricao", length = 100)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "valor", nullable = false, length = 200)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

}
