package br.com.model;

// Generated 08/03/2012 15:36:20 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * Vendaitem generated by hbm2java
 */
@Entity
@Table(name = "vendaitem", catalog = "qualisono")
public class VendaItem implements java.io.Serializable {

	private Integer codigo;
	private Produto produto;
	private Venda venda;
	private Unidade unidade;
	private int quantidade;
	private int pontuacao;
	private double valor;
	private double comissaopd;
	private double comissaom;
	private double desconto;
	private String tipodesconto;

	public VendaItem() {
	}

	public VendaItem(Produto produto, Venda venda, Unidade unidade,
			int quantidade, int pontuacao, double valor,
			double comissaopd, double comissaom, double desconto, String tipodesconto) {
		this.produto = produto;
		this.venda = venda;
		this.unidade = unidade;
		this.quantidade = quantidade;
		this.pontuacao = pontuacao;
		this.valor = valor;
		this.comissaopd = comissaopd;
		this.comissaom = comissaom;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false)
	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "produto", nullable = false)
	public Produto getProduto() {
		return this.produto;
	}

	public void setProduto(Produto produto) {
		this.produto = produto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "venda", nullable = false)
	public Venda getVenda() {
		return this.venda;
	}

	public void setVenda(Venda venda) {
		this.venda = venda;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unidade", nullable = false)
	public Unidade getUnidade() {
		return this.unidade;
	}

	public void setUnidade(Unidade unidade) {
		this.unidade = unidade;
	}

	@NotNull(message="Campo Quantidade: Obrigatório")
	@Column(name = "quantidade", nullable = false)
	public int getQuantidade() {
		return this.quantidade;
	}

	public void setQuantidade(int quantidade) {
		this.quantidade = quantidade;
	}

	@Column(name = "pontuacao", nullable = false)
	public int getPontuacao() {
		return this.pontuacao;
	}

	public void setPontuacao(int pontuacao) {
		this.pontuacao = pontuacao;
	}

	@Column(name = "valor", nullable = false, precision = 15)
	public double getValor() {
		return this.valor;
	}

	public void setValor(double valor) {
		this.valor = valor;
	}

	@Column(name = "comissaopd", nullable = false, precision = 5)
	public double getComissaopd() {
		return this.comissaopd;
	}

	public void setComissaopd(double comissaopd) {
		this.comissaopd = comissaopd;
	}

	@Column(name = "comissaom", nullable = false, precision = 5)
	public double getComissaom() {
		return this.comissaom;
	}

	public void setComissaom(double comissaom) {
		this.comissaom = comissaom;
	}
	
	@Column(name = "tipodesconto", length = 200)
	public String getTipodesconto() {
		return this.tipodesconto;
	}

	public void setTipodesconto(String tipodesconto) {
		this.tipodesconto = tipodesconto;
	}
	
	@Column(name = "desconto", nullable = false, precision = 9)
	public double getDesconto() {
		return this.desconto;
	}

	public void setDesconto(double desconto) {
		this.desconto = desconto;
	}

}
